INSERT INTO listings
(seller_id, title, description, price, is_sold, item_condition, brand, model, main_image_id, category_id, meeting_location) VALUES
(2, 'Calculus Textbook', 'Comprehensive calculus guide, great condition', 30.00, FALSE, 'Used', NULL, NULL, NULL, 1, 'Library'),
(2, 'HP Pavilion Laptop', 'Lightly used HP laptop, perfect for students', 450.00, FALSE, 'Like New', 'HP', 'Pavilion', NULL, 6, 'Dorm'),
(2, 'iPhone 12 Pro Max Case', 'Brand new iPhone case, never used', 15.00, FALSE, 'New', 'Apple', 'iPhone 12 Pro Max', NULL, 10, 'Library'),
(2, 'Soccer Game Ticket - University vs. State', 'One ticket for the upcoming soccer match', 20.00, FALSE, 'New', NULL, NULL, NULL, 12, 'Stadium'),
(2, 'The Great Gatsby - Novel', 'Classic literature, good condition', 8.00, FALSE, 'Used', NULL, NULL, NULL, 2, 'Duncan Students Center'),
(2, 'Yoga Mat', 'High-quality yoga mat, barely used', 25.00, FALSE, 'Like New', NULL, NULL, NULL, 16, 'Gym'),
(2, 'Graphic Calculator', 'TI-84 Plus, great for engineering students', FALSE, 60.00, 'Used', 'Texas Instruments', 'TI-84 Plus', NULL, 1, 'Library'),
(2, 'Basketball Shoes', 'Size 10, good condition', 50.00, FALSE, 'Used', 'Nike', 'Air Jordan', NULL, 16, 'Sports Complex'),
(2, 'Wireless Keyboard', 'Compact and lightweight', 20.00, FALSE, 'Like New', 'Logitech', 'K380', NULL, 6, 'Dorm'),
(2, 'Concert Ticket - Pop Band', 'Front row seats for the summer concert', 100.00, FALSE, 'New', NULL, NULL, NULL, 14, 'Auditorium'),
(2, 'Study Lamp', 'LED, adjustable brightness', 15.00, FALSE, 'Used', NULL, NULL, NULL, 5, 'Dorm'),
(2, 'Bluetooth Speaker', 'Portable, high-quality sound', 30.00, FALSE, 'Like New', 'JBL', 'Flip 5', NULL, 7, 'Dorm'),
(2, 'E-reader', 'Kindle Paperwhite, great for reading', 80.00, FALSE, 'Like New', 'Amazon', 'Kindle Paperwhite', NULL, 6, 'Library'),
(2, 'Fitness Watch', 'Tracks steps and sleep', 70.00, FALSE, 'Used', 'Fitbit', 'Versa', NULL, 16, 'Gym'),
(2, 'Backpack', 'Durable, lots of pockets', 35.00, FALSE, 'Used', 'North Face', NULL, NULL, 15, 'Student Center'),
(2, 'Acoustic Guitar', 'Good condition, great sound', 120.00, FALSE, 'Used', 'Yamaha', 'FG800', NULL, 17, 'Music Room'),
(2, 'Desk Chair', 'Ergonomic and comfortable', 40.00, FALSE, 'Used', 'Ikea', 'Markus', NULL, 5, 'Dorm'),
(2, 'Water Bottle', 'Insulated, 1L capacity', 10.00, FALSE, 'Like New', 'Hydro Flask', NULL, NULL, 16, 'Gym'),
(2, 'Soccer Ball', 'FIFA approved, size 5', 18.00, FALSE, 'New', 'Adidas', 'Telstar', NULL, 16, 'Sports Field'),
(2, 'USB Flash Drive', '64GB, USB 3.0', 15.00, FALSE, 'New', 'SanDisk', NULL, NULL, 6, 'Library'),
(2, 'Sweatshirt', 'Size M, university logo', 20.00, FALSE, 'Used', NULL, NULL, NULL, 14, 'Bookstore'),
(2, 'Hiking Boots', 'Waterproof, size 9', 60.00, FALSE, 'Like New', 'Merrell', 'Moab 2', NULL, 16, 'Outdoor Center'),
(2, 'Wireless Mouse', 'Ergonomic, long battery life', 25.00, FALSE, 'Used', 'Logitech', 'MX Master 3', NULL, 6, 'Dorm'),
(2, 'Cookware Set', 'Non-stick, 5 pieces', 50.00, FALSE, 'New', 'T-fal', NULL, NULL, 13, 'Dorm Kitchen'),
(2, 'Travel Mug', 'Stainless steel, vacuum insulated', 12.00, FALSE, 'Like New', 'Contigo', NULL, NULL, 13, 'Cafeteria');
